import dedent from "ts-dedent";
import { CLIError } from "../cli-error";

/**
 * Thrown when a `.d.ts` file already exists at the output path but was not
 * generated by Wrangler. To avoid overwriting user-authored declarations,
 * the user must rename the existing file first.
 */
export class ConflictingTypesFileError extends CLIError {
	/**
	 * @param fileName - The base name of the conflicting file
	 *   (e.g. `"worker-configuration.d.ts"`).
	 */
	constructor(fileName: string) {
		const humanMessage = `A non-Wrangler ${fileName} already exists, please rename and try again.`;

		const aiMessage = dedent`
			## Error: Conflicting Types File

			A file named \`${fileName}\` already exists and was not generated by Wrangler.

			### What happened
			\`wrangler types\` wants to write to this file, but it already contains
			user-authored or third-party type declarations. Overwriting it could
			destroy custom types.

			### How to fix
			- Rename the existing \`${fileName}\` to a different name
			- Or specify a different output path: \`wrangler types my-worker-types.d.ts\`
			- After renaming, re-run \`wrangler types\`

			### Question to ask the human
			To better resolve this issue, consider asking the human developer the following:
			- Should the existing \`${fileName}\` be renamed? If so, to what?
			- Or should Wrangler output to a different file?
		`;

		super(humanMessage, aiMessage, {
			telemetryMessage: "type generation validation conflicting types file",
		});
	}
}
